func_part:
  name: call_jm
  description: jmcomic漫画查询、预览、下载。“验车”是预览的另一种称呼
  parameters:
    type: object
    properties:
      mode: 
        type: string,
        enum:
        - preview
        - download
        - search
        description: 预览和下载需要comic_id，搜索需要query_target
      comic_id: 
        type: integer,
        description: 漫画id。预览和下载时使用
      serach_topic:
        type: string,
        description: 搜索关键字
    required:
      - mode
funcs:
  - name: call_jm
    description: 调用jmcomic的漫画查询、预览、下载接口
    importfrom: extensions.jmcomic.func.jmcomic
ordinary_funcs:   #普通指令触发函数
  - name: query_comic
    description: 查询漫画信息
    trigger_rule:
      - startswith: 验车
    examples:
      - 验车350234